version: '2'
services:
    rimrowad-app:
        image: rimrowad
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rimrowad-mysql:3306/rimrowad?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rimrowad-mysql:
        extends:
            file: mysql.yml
            service: rimrowad-mysql
